from issem.forms.departamento import DepartamentoForm
from issem.forms.tipo_exame import Tipo_ExameForm
from issem.forms.tipo_dependente import Tipo_DependenteForm
from issem.forms.beneficio import BeneficioForm
from issem.forms.cargo import CargoForm
from issem.forms.cid import CidForm
from issem.forms.estado_civil import Estado_CivilForm
from issem.forms.funcao import FuncaoForm
from issem.forms.procedimento_medico import Procedimento_MedicoForm
from issem.forms.tipo_sangue import Tipo_SangueForm
