from issem.views.beneficio import *
from issem.views.cargo import *
from issem.views.cid import *
from issem.views.departamento import *
from issem.views.funcao import *
from issem.views.index import *
from issem.views.procedimento_medico import *
from issem.views.tipo_dependente import *
from issem.views.tipo_exame import *
from issem.views.tipo_sangue import *
from issem.views.estado_civil import *
from issem.views.secretaria import *
from issem.views.local_trabalho import *
from issem.views.dependente import *
from issem.views.segurado import *