from issem.views.beneficio import *
from issem.views.cargo import *
from issem.views.cid import *
from issem.views.cidade import *
from issem.views.consulta_parametros import *
from issem.views.contato_issem import *
from issem.views.dependente import *
from issem.views.funcao import *
from issem.views.funcionario_pagina import *
from issem.views.gera_agendamento_servidor import *
from issem.views.index import *
from issem.views.lixeira.departamento import *
from issem.views.local_trabalho import *
from issem.views.medico_pagina import *
from issem.views.procedimento_medico import *
from issem.views.requerimento import *
from issem.views.requerimento_servidor import *
from issem.views.secretaria import *
from issem.views.segurado import *
from issem.views.segurado_pagina import *
from issem.views.segurado_pagina import *
from issem.views.servidor import *
from issem.views.tipo_dependente import *
from issem.views.tipo_exame import *
from issem.views.contato_issem import *
