from issem.models import Beneficio
from issem.models import Cargo
from issem.models import Cid
from issem.models import Estado
from issem.models import Cidade
from issem.models import Departamento
from issem.models import Estado_Civil
from issem.models import Funcao
from issem.models import Procedimento_Medico
from issem.models import Tipo_Dependente
from issem.models import Tipo_Exame
from issem.models import Tipo_Sangue