from issem.models.beneficio import BeneficioModel
from issem.models.cargo import CargoModel
from issem.models.cid import CidModel
from issem.models.cidade import CidadeModel
from issem.models.departamento import DepartamentoModel
from issem.models.dependente import DependenteModel
from issem.models.estado import EstadoModel
from issem.models.estado_civil import EstadoCivilModel
from issem.models.funcao import FuncaoModel
from issem.models.local_trabalho import LocalTrabalhoModel
from issem.models.pessoa import PessoaModel
from issem.models.procedimento_medico import ProcedimentoMedicoModel
from issem.models.secretaria import SecretariaModel
from issem.models.segurado import SeguradoModel
from issem.models.servidor import ServidorModel
from issem.models.tipo_dependente import TipoDependenteModel
from issem.models.tipo_exame import TipoExameModel
from issem.models.tipo_sangue import TipoSangueModel
